CREATE DATABASE IF NOT EXISTS syncspace_db;
USE syncspace_db;
CREATE TABLE users (
id INT PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(30) NOT NULL UNIQUE,
password_hash VARCHAR(255) NOT NULL,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE messages (
id BIGINT PRIMARY KEY AUTO_INCREMENT,
sender_id INT NOT NULL,
content VARCHAR(1000) NOT NULL,
sent_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

CONSTRAINT fk_messages_sender
FOREIGN KEY (sender_id)
REFERENCES users(id)
);
USE syncspace_db;
SHOW TABLES;